### ISSUE TITLE
Publish() causes a runtime error when no client subscribed to then channel.

### ISSUE THREAD

**Issue by jtbonhomme** [centrifugal/centrifuge#316]
**Describe the bug**
Calling the node method `Publish()` causes a runtime error when no client subscribed to the channel.

**To Reproduce**
1. Run following server code:
```go
package main

import (
    "fmt"
    "github.com/centrifugal/centrifuge"
)

func handleLog(e centrifuge.LogEntry) {
    fmt.Printf("%s: %v", e.Message, e.Fields)
}

func main() {
    fmt.Println("starting ...")

    fmt.Println("create centrifuge node ...")
    node, err := centrifuge.New(centrifuge.Config{
        LogLevel:   centrifuge.LogLevelDebug,
        LogHandler: handleLog,
    })
    if err != nil {
        panic(fmt.Errorf("error creating centrifuge node: %s", err.Error()))
    }

    fmt.Println("publish message ...")
    node.Publish("test-channel", []byte(`{"key":"value"}`))
    if err != nil {
        panic(fmt.Errorf("manager publication error: %s", err.Error()))
    }
}
```
2. See error
```
❯ go run main.go
starting ...
create centrifuge node ...
publish message ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x13f7b32]

goroutine 1 [running]:
github.com/centrifugal/centrifuge.(*MemoryBroker).Publish(0xc000129080, {0x15145a1, 0xc}, {0xc00032ec80, 0xf, 0xf}, {0x0, 0x0, 0x0, 0x0, ...})
	/Users/jbonhomm/Documents/Developpements/golang/pkg/mod/github.com/centrifugal/centrifuge@v0.30.0/broker_memory.go:100 +0x352
github.com/centrifugal/centrifuge.(*Node).publish(0xc000326000, {0x15145a1, 0xc}, {0xc00032ec80, 0xf, 0xf}, {0x0, 0x0, 0x5d21dba00?})
	/Users/jbonhomm/Documents/Developpements/golang/pkg/mod/github.com/centrifugal/centrifuge@v0.30.0/node.go:726 +0x142
github.com/centrifugal/centrifuge.(*Node).Publish(...)
	/Users/jbonhomm/Documents/Developpements/golang/pkg/mod/github.com/centrifugal/centrifuge@v0.30.0/node.go:758
main.main()
	/Users/jbonhomm/Documents/Developpements/golang/src/github.com/centrifugal/issue/main.go:25 +0x19d
exit status 2
```

**Expected behavior**

I expect nothing to happen and a nil error to be returned.

**Versions (please complete the following information):**
 - OS: MacOS BigSur 11.7.6
 - Client SDK version: n/a
 - Server version `github.com/centrifugal/centrifuge v0.30.0`

**Additional context**
I could check in my own program that with at least one client connected and having subscribed to the channel, the runtime error is not triggered.

**Comment by FZambia** [comment]
Hello @jtbonhomme 

You need to call `node.Run()` - check out all the examples, like this one: https://github.com/centrifugal/centrifuge/blob/7e66db91832408ed8e5f66986a3c2d06be099308/_examples/chat_json/main.go#L202

**Comment by jtbonhomme** [comment]
Thank you for your quick answer Alexander,
It works now !
