### ISSUE TITLE
ujson breaks test_response tests

### ISSUE THREAD

**Issue by flc** [centrifugal/centrifuge#56]
if ujson is installed it breaks the test_response tests due to the fact that it compresses the generated json by removing whitespaces.

```python
======================================================================
FAIL: test_response (test.test_response.MultiResponseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/flc/src/centrifuge-flc/test/test_response.py", line 52, in test_response
    self.assertEqual(response_message, json.dumps(response_list))
AssertionError: '[{"body":"test_body","error":"test_error","uid":"test_uid","method":"test_method"},{"body":"test_body","error":"test_error","uid":"test_uid","method":"test_method"}]' != '[{"body": "test_body", "error": "test_error", "uid": "test_uid", "method": "test_method"}, {"body": "test_body", "error": "test_error", "uid": "test_uid", "method": "test_method"}]'

======================================================================
FAIL: test_response (test.test_response.ResponseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/flc/src/centrifuge-flc/test/test_response.py", line 28, in test_response
    self.assertEqual(response_message, json.dumps(response_dict))
AssertionError: '{"body":"test_body","error":"test_error","uid":"test_uid","method":"test_method"}' != '{"body": "test_body", "error": "test_error", "uid": "test_uid", "method": "test_method"}'

----------------------------------------------------------------------

```

**Comment by FZambia** [comment]
Thanks, fixed! To be fair test coverage is a weak side of Centrifuge. I am planning to improve situation but have no enough time at moment.
